app/authentication/routes.py
from forms import UserLoginForm, UserSignUpForm
from models import User, db, check_password_hash, generate_password_hash, user_schema
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify # try to make flash work
from helpers import token_required

from flask_login import login_user, logout_user, LoginManager, current_user, login_required

import time

auth = Blueprint('auth', __name__, template_folder = 'auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserSignUpForm()

    try:
        if request.method == 'POST':
            # email = form.email.data
            # confirm_email = form.confirm_email.data
            # password = form.password.data
            # confirm_password = form.confirm_password.data
            data = request.get_json()
            email = data['email']
            confirm_email = data['confirmEmail']
            password = data['password']
            confirm_password = data['confirmPassword']

            if email == confirm_email and password == confirm_password:
                user = User(email, password = password)

                db.session.add(user)
                db.session.commit()
            
                flash(f'You have successfully created a user account for {email}. Redirecting in 3 seconds...', 'User-created')

                time.sleep(3)

                # return redirect(url_for('site.home'))
                return jsonify({'message': 'Account created successfully!'}), 201

            else:
                # flash('Username or Password does not match.')
                return jsonify({'error': 'Email or Password do not match.'}), 400
    
    except:
        raise Exception('Invalid entry: Please try again.')

    return render_template('sign_up.html', form = form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    print(request.data)
    print(request.get_json())

    data = request.get_json()
    email = data['email']
    password = data['password']
    try:
        if request.method == 'POST':
            # email = form.email.data
            # password = form.password.data
            print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                token = logged_user.token

                return jsonify({"token": token})
                
            else:
                
                return jsonify({"error": "Invalid Email or Password."}), 401
    except:
        raise Exception('Invalid entry: Please try again.')
    return 'test'

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('site.home'))

# change first name and last name
@auth.route('/update-data', methods = ['PUT'])
@token_required
def update_user_data(current_user_token):
    data = request.get_json()
    token = current_user_token.token

    user = User.query.filter(User.token == token).first()

    if not user:
        return 'User not found or incorrect token', 404
    
    if not token:
        return 'Token not found', 404
    
    try:
        user.first_name = request.json.get('first_name', user.first_name)
        user.last_name = request.json.get('last_name', user.last_name)
        db.session.commit()
    except:
        raise Exception('Missing required data.')

# change password
@auth.route('/update-password', methods = ['PUT'])
@token_required
def update_password(current_user_token):
    data = request.get_json()
    token = current_user_token.token
    old_password = data['old_password']
    new_password = data['new_password']

    user = User.query.filter(User.token == token).first()

    if not user:
        return 'User not found', 404
    
    if not token:
        return 'Invalid token or token not found', 404
    
    if not old_password or not new_password:
        return 'Incorrect or missing password.', 404
    
    if user and check_password_hash(user.password, old_password):
        new_pw_hash = generate_password_hash(new_password)
        user.password = new_pw_hash

        db.session.commit()

        return jsonify({'message': 'Password Updated!'}), 201
    return 'test'


# get data to display on front end
@auth.route('/get-user-data', methods = ['GET'])
@token_required
def get_user_data(current_user_token):
    token = current_user_token.token

    user = User.query.filter(User.token == token).first()

    if not user:
        return 'User not found', 404

    response = user_schema.dump(user)
    return jsonify(response)

app/site/routes.py
from flask import Blueprint, render_template

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
def profile():
    return render_template('profile.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="assets/css/style.css">
<title>StashTracker</title>
</head>
<body>
    <div class="navbar navbar-expand-lg" id="navmenu">
        <div class="container-fluid">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a href="{{ url_for('site.home') }}" class="nav-link">Home</a>
                </li>
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a href="{{ url_for('site.profile') }}" class="nav-link">Profile</a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('auth.logout') }}" class="nav-link">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a href="{{ url_for('auth.signin') }}" class="nav-link">Sign In</a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('auth.signup') }}" class="nav-link">Sign Up</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>

    {% block content %}
    {% endblock %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/sign_in_form.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div>
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control") }}
        </fieldset>
    </div>
    <div>
        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control") }}
        </fieldset>
    </div>
    <div>
        {{ form.submit_button(class = "btn btn-primary") }}
    </div>
</form>

app/templates/sign_up_form.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div>
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control") }}
        </fieldset>
        <fieldset id="confirm-email-field">
            {{ form.confirm_email.label }}
            {{ form.confirm_email(class = "form-control") }}
        </fieldset>
    </div>
    <div>
        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control") }}
        </fieldset>
        <fieldset id="confirm-pass-field">
            {{ form.confirm_password.label }}
            {{ form.confirm_password(class = "form-control") }}
        </fieldset>
    </div>
    <div>
        {{ form.submit_button(class = "btn btn-primary") }}
    </div>
</form>